name: Build and deploy CIPP API to Azure Function App - cippqk5zf-auditlog

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PowerShell 7.4
        uses: PowerShell/setup-powershell@v2
        with:
          pwsh-version: '7.4'

      - name: Zip function app
        run: |
          zip -r functionapp.zip .

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'cippqk5zf-auditlog'
          package: 'functionapp.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_AUDITLOG }}
